from common.data import DataLabel, DataSource
from rewards.data import DataSourceReward, RewardDistributionModel


# Pydantic can't serialize a model to json when it has dictionaries with
# non-primitive keys. There are probably ways to write a custom serializer/deserializer,
# but for now, we'll just write the model in code, because it's easy enough to read.

# The benefit of the extra validation and standardization provided by DataLabel outweighs
# the cost of not being able to serialize the model to json.

DISTRIBUTION = RewardDistributionModel(
    distribution={
        DataSource.REDDIT: DataSourceReward(
            weight=0.5,
            default_scale_factor=0.5,
            # The following labels were pulled from the top 1XX subreddits relating to cryptocurrency.
            # We welcome feedback on this list. Please file an Issue on the github with your suggestions.
            label_scale_factors={
                DataLabel(value="0xProject"): 1.0,
                DataLabel(value="1inch"): 1.0,
                DataLabel(value="Aave_Official"): 1.0,
                DataLabel(value="aelfofficial"): 1.0,
                DataLabel(value="amptoken"): 1.0,
                DataLabel(value="AragonProject"): 1.0,
                DataLabel(value="Arweave"): 1.0,
                DataLabel(value="Avax"): 1.0,
                DataLabel(value="AxieInfinity"): 1.0,
                DataLabel(value="BATProject"): 1.0,
                DataLabel(value="BinanceUSD"): 1.0,
                DataLabel(value="BittorrentToken"): 1.0,
                DataLabel(value="Bitcoin"): 1.0,
                DataLabel(value="BitcoinCash"): 1.0,
                DataLabel(value="BitcoinGoldHQ"): 1.0,
                DataLabel(value="Bitfinex"): 1.0,
                DataLabel(value="Bitcoinsv"): 1.0,
                DataLabel(value="Bittensor"): 1.0,
                DataLabel(value="BNBTrader"): 1.0,
                DataLabel(value="CeloHQ"): 1.0,
                DataLabel(value="Chainlink"): 1.0,
                DataLabel(value="Chia"): 1.0,
                DataLabel(value="ChiliZ"): 1.0,
                DataLabel(value="Compound"): 1.0,
                DataLabel(value="CRO"): 1.0,
                DataLabel(value="Cryptocurrency"): 1.0,
                DataLabel(value="CurveDAO"): 1.0,
                DataLabel(value="Dashpay"): 1.0,
                DataLabel(value="Decentraland"): 1.0,
                DataLabel(value="DFinity"): 1.0,
                DataLabel(value="DFinity"): 1.0,
                DataLabel(value="Dogecoin"): 1.0,
                DataLabel(value="Dogelon"): 1.0,
                DataLabel(value="Ecash"): 1.0,
                DataLabel(value="ElrondNetwork"): 1.0,
                DataLabel(value="EnjinCoin"): 1.0,
                DataLabel(value="EOS"): 1.0,
                DataLabel(value="Ergonauts"): 1.0,
                DataLabel(value="EthereumClassic"): 1.0,
                DataLabel(value="EthereumClassic"): 1.0,
                DataLabel(value="ETHTrader"): 1.0,
                DataLabel(value="Ethtrader"): 1.0,
                DataLabel(value="FantomFoundation"): 1.0,
                DataLabel(value="Fei Protocol"): 1.0,
                DataLabel(value="Filecoin"): 1.0,
                DataLabel(value="FlowBlockchain"): 1.0,
                DataLabel(value="FTXOfficial"): 1.0,
                DataLabel(value="GALACOIN"): 1.0,
                DataLabel(value="GateioExchange"): 1.0,
                DataLabel(value="Gemini"): 1.0,
                DataLabel(value="GnosisPM"): 1.0,
                DataLabel(value="Harmony_One"): 1.0,
                DataLabel(value="HelloIcon"): 1.0,
                DataLabel(value="HeliumNetwork"): 1.0,
                DataLabel(value="Hedera"): 1.0,
                DataLabel(value="Holochain"): 1.0,
                DataLabel(value="HuobiGlobal"): 1.0,
                DataLabel(value="Iota"): 1.0,
                DataLabel(value="Kadena"): 1.0,
                DataLabel(value="KavaLabs"): 1.0,
                DataLabel(value="Klaytn"): 1.0,
                DataLabel(value="Kusama"): 1.0,
                DataLabel(value="Kucoin"): 1.0,
                DataLabel(value="Litecoin"): 1.0,
                DataLabel(value="Loopringorg"): 1.0,
                DataLabel(value="MakerDAO"): 1.0,
                DataLabel(value="MakerDAO"): 1.0,
                DataLabel(value="MinaProtocol"): 1.0,
                DataLabel(value="Monero"): 1.0,
                DataLabel(value="Nanocurrency"): 1.0,
                DataLabel(value="NearProtocol"): 1.0,
                DataLabel(value="NEO"): 1.0,
                DataLabel(value="NEM"): 1.0,
                DataLabel(value="NervosNetwork"): 1.0,
                DataLabel(value="OntologyNetwork"): 1.0,
                DataLabel(value="OMGNetwork"): 1.0,
                DataLabel(value="Pancakeswap"): 1.0,
                DataLabel(value="PaxG"): 1.0,
                DataLabel(value="Polkadot"): 1.0,
                DataLabel(value="ProtonChain"): 1.0,
                DataLabel(value="QTUM"): 1.0,
                DataLabel(value="Rardor"): 1.0,
                DataLabel(value="Ravencoin"): 1.0,
                DataLabel(value="SafeMoon"): 1.0,
                DataLabel(value="SHIBArmy"): 1.0,
                DataLabel(value="Solana"): 1.0,
                DataLabel(value="Stacks"): 1.0,
                DataLabel(value="StepN"): 1.0,
                DataLabel(value="Stellar"): 1.0,
                DataLabel(value="Tao"): 1.0,
                DataLabel(value="Tezos"): 1.0,
                DataLabel(value="Tether"): 1.0,
                DataLabel(value="TheGraph"): 1.0,
                DataLabel(value="TheSandboxGaming"): 1.0,
                DataLabel(value="Theta_Network"): 1.0,
                DataLabel(value="Tronix"): 1.0,
                DataLabel(value="TrustToken"): 1.0,
                DataLabel(value="Uniswap"): 1.0,
                DataLabel(value="USDC"): 1.0,
                DataLabel(value="Vechain"): 1.0,
                DataLabel(value="Wavesplatform"): 1.0,
                DataLabel(value="WrappedBitcoin"): 1.0,
                DataLabel(value="Xinfin"): 1.0,
                DataLabel(value="Zec"): 1.0,
                DataLabel(value="Zilliqa"): 1.0,
            },
        ),
        DataSource.X: DataSourceReward(
            weight=0.5,
            default_scale_factor=0.5,
            label_scale_factors={
                DataLabel(value="#bitcoin"): 1.0,
                DataLabel(value="#bitcoincharts"): 1.0,
                DataLabel(value="#bitcoiner"): 1.0,
                DataLabel(value="#bitcoinexchange"): 1.0,
                DataLabel(value="#bitcoinmining"): 1.0,
                DataLabel(value="#bitcoinnews"): 1.0,
                DataLabel(value="#bitcoinprice"): 1.0,
                DataLabel(value="#bitcointechnology"): 1.0,
                DataLabel(value="#bitcointrading"): 1.0,
                DataLabel(value="#bittensor"): 1.0,
                DataLabel(value="#blockchain"): 1.0,
                DataLabel(value="#btc"): 1.0,
                DataLabel(value="#cryptocurrency"): 1.0,
                DataLabel(value="#crypto"): 1.0,
                DataLabel(value="#defi"): 1.0,
                DataLabel(value="#decentralizedfinance"): 1.0,
                DataLabel(value="#entrepreneur"): 1.0,
                DataLabel(value="#investing"): 1.0,
                DataLabel(value="#money"): 1.0,
                DataLabel(value="#nfts"): 1.0,
                DataLabel(value="#satoshi"): 1.0,
                DataLabel(value="#success"): 1.0,
                DataLabel(value="#tao"): 1.0,
                DataLabel(value="#technology"): 1.0,
                DataLabel(value="#trading"): 1.0,
                DataLabel(value="#wealth"): 1.0,
            },
        ),
    },
    max_age_in_hours=7 * 24,
)
